# --- Fonte e Legibilidade ---
font_family      FiraCode Nerd Font
font_size        11.0
bold_font        auto
italic_font      auto
disable_ligatures never

# --- Estética da Janela ---
background_opacity         0.85
dynamic_background_opacity yes
window_padding_width       15
confirm_os_window_close    0

# --- Cores Tokyo Night ---
# foreground            #a9b1d6
# background            #1a1b26
# selection_foreground  #1a1b26
# selection_background  #7aa2f7

# Cores das abas
# active_tab_foreground   #1a1b26
# active_tab_background   #7aa2f7
# inactive_tab_foreground #a9b1d6
# inactive_tab_background #24283b

# --- Cursor ---
# cursor                #c0caf5
# cursor_text_color     #1a1b26
cursor_shape          beam
cursor_beam_thickness 1.5

# --- Atalhos Úteis ---
map ctrl+shift+enter new_window
map ctrl+shift+t     new_tab
map ctrl+shift+w     close_tab


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
