foreground            #f3ddde
background            #1b1111
selection_foreground  #67001e
selection_background  #ffb2b9
url_color             #80d9a4
cursor                #ffb2b9
cursor_text_color     #67001e

color0   #1b1111
color1   #ffb4ab
color2   #ffb2b9
color3   #80d9a4
color4   #ffb2b9
color5   #80d9a4
color6   #006e43
color7   #f3ddde

color8   #a58a8c
color9   #ffb4ab
color10  #ffb2b9
color11  #80d9a4
color12  #ffb2b9
color13  #80d9a4
color14  #006e43
color15  #f3ddde

tab_bar_background              #1b1111
tab_bar_margin_color            #1b1111
active_tab_foreground           #67001e
active_tab_background           #ffb2b9
inactive_tab_foreground         #debfc1
inactive_tab_background         #1b1111
