color0 #131316
color1 #ffb4ab
color2 #bfc3f6
color3 #c5c4db
color4 #eeb6dd
color5 #bfc3f6
color6 #c5c4db
color7 #e5e1e6
color8 #919099
color9 #ffb4ab
color10 #bfc3f6
color11 #c5c4db
color12 #eeb6dd
color13 #bfc3f6
color14 #c5c4db
color15 #e5e1e6

cursor                #e5e1e6
cursor_text_color     #131316
background            #131316
foreground            #e5e1e6
selection_foreground  #c7c5d0
selection_background  #46464e
active_border_color   #bfc3f6
inactive_border_color #46464e
url_color             #bfc3f6

active_tab_foreground   #292d57
active_tab_background   #bfc3f6
inactive_tab_foreground #c7c5d0
inactive_tab_background #46464e
cursor_trail_color      #c7c5d0
